# SEP532 - 인공지능 이론과 실제 (2022 Spring)
## Deep Learning Practice 
#### Prof. Ho-Jin Choi
#### School of Computing, KAIST

---

# 3. Intorduction to TensorFlow

## Introduction to Tensorflow   
- [**TensorFlow**](https://www.tensorflow.org) is a software library, developed by Google Brain Team within Google's Machine Learning Intelligence research organization, for the purposes of conducting machine learning and deep neural network research.
- TensorFlow combines the computational algebra of compilation optimization techniques, making easy the calculation of many mathematical expressions that would be difficult to calculate, instead.

### Main features
* Defining, optimizing, and efficiently calculating mathematical expressions involving multi-dimensional arrays (tensors).
* Programming support of **deep neural networks** and machine learning techniques.
* Transparent use of GPU computing, automating management and optimization of the same memory and the data used. You can write the same code and run it either on CPUs or GPUs. More specifically, TensorFlow will figure out which parts of the computation should be moved to the GPU.
* High scalability of computation across machines and huge data sets.


## Handling Tensor based on eager execution

TensorFlow is called TensorFlow because it handles the flow (node/mathematical operation) of Tensors (data), which you can think of as multidimensional arrays. In TensorFlow, computations can be thought of as graphs. In the previous version (<1.14) of Tensorflow, we implemented a computation graph thought a session we defined and ran the graphs in the session. But, the latest version does not use the session, it can be used simply through an eager executation.

[**Eager execution**](https://www.tensorflow.org/guide/eager) is an imperative programming environment that evaluates operations immediately, without building graphs: operations return concrete values instead of constructing a computational graph to run later. This makes it easy to get started with TensorFlow and debug models, and it reduces boilerplate as well.

In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

# Install TensorFlow
try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 2.x
except Exception:
    pass

import tensorflow as tf
print('Tensorflow: ', tf.__version__)

import cProfile
import numpy as np
import matplotlib.pyplot as plt

Tensorflow:  2.7.0


In [2]:
# In Tensorflow 2.0, eager execution is enabled by default.
tf.executing_eagerly()

True

In [ ]:
from google.colab import drive
drive.mount('/gdrive')

import os

gdrive_root = '/gdrive/My Drive'
print('In gdrive :', os.listdir(gdrive_root))

### Tensor

A **tensor** is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes.

In [3]:
# Construct a 3x4 tensor, filled with zeros
x = tf.zeros([3, 4], tf.int32)
print(x, '\n')

# Construct a 3x4 tensor, filled with ones
x = tf.ones([3, 4], tf.int32)
print(x, '\n')

# Construct a 1-dimension tensor with constant values
x = tf.constant([1, 2.5, 4.6, 5.75, 9.7])
print(x, '\n')

# Construct a 2x2 tensor with constant values
x = tf.constant((np.arange(16).reshape(4, 4)))
print(x, '\n')

# Convert a numpy array to tensor
x = tf.convert_to_tensor(np.array([1,2,3]))
print(x, '\n')

# Obtain numpy value from a tensor:
x = x.numpy()
print(x)

tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32) 

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32) 

tf.Tensor([1.   2.5  4.6  5.75 9.7 ], shape=(5,), dtype=float32) 

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]], shape=(4, 4), dtype=int64) 

tf.Tensor([1 2 3], shape=(3,), dtype=int64) 

[1 2 3]


### Arithmetic operations

In [4]:
A = tf.constant([
    [4, 3],
    [1, 1],
], dtype=tf.float32, name='A')

B = tf.constant([
    [3, 5],
    [1, 2],
], dtype=tf.float32, name='B')

In [6]:
print('A + B =', tf.add(A, B))
print('A - B =', tf.subtract(A, B))
print('A ⨉ B =', tf.matmul(A, B))
print('A * B =', tf.multiply(A, B))
print('A² =', tf.square(A))
print('sum(A) =', tf.reduce_sum(A))
print('det(A) =', tf.linalg.det(A))
print('inv(A) =', tf.linalg.inv(A))
print('A ⨉ inv(A) =', tf.matmul(A, tf.linalg.inv(A)))

A + B = tf.Tensor(
[[7. 8.]
 [2. 3.]], shape=(2, 2), dtype=float32)
A - B = tf.Tensor(
[[ 1. -2.]
 [ 0. -1.]], shape=(2, 2), dtype=float32)
A ⨉ B = tf.Tensor(
[[15. 26.]
 [ 4.  7.]], shape=(2, 2), dtype=float32)
A * B = tf.Tensor(
[[12. 15.]
 [ 1.  2.]], shape=(2, 2), dtype=float32)
A² = tf.Tensor(
[[16.  9.]
 [ 1.  1.]], shape=(2, 2), dtype=float32)
sum(A) = tf.Tensor(9.0, shape=(), dtype=float32)
det(A) = tf.Tensor(1.0, shape=(), dtype=float32)
inv(A) = tf.Tensor(
[[ 1. -3.]
 [-1.  4.]], shape=(2, 2), dtype=float32)
A ⨉ inv(A) = tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)


### Broadcasting

Broadcasting is a concept borrowed from the equivalent feature in NumPy. In short, under certain conditions, smaller tensors are "stretched" automatically to fit larger tensors when running combined operations on them.

The simplest and most common case is when you attempt to multiply or add a tensor to a scalar. In that case, the scalar is broadcast to be the same shape as the other argument.

In [7]:
# Operator overloading is supported
print('A + B = ', A + B)
print('A - B = ', A - B)
print('A @ B = ', A @ B) # matrix multiplication
print('A * B = ', A * B) # Element-wise 
print('A / B = ', A / B)

# Broadcasting support
print('A + 1 = ', tf.add(A, 1))

A + B =  tf.Tensor(
[[7. 8.]
 [2. 3.]], shape=(2, 2), dtype=float32)
A - B =  tf.Tensor(
[[ 1. -2.]
 [ 0. -1.]], shape=(2, 2), dtype=float32)
A @ B =  tf.Tensor(
[[15. 26.]
 [ 4.  7.]], shape=(2, 2), dtype=float32)
A * B =  tf.Tensor(
[[12. 15.]
 [ 1.  2.]], shape=(2, 2), dtype=float32)
A / B =  tf.Tensor(
[[1.3333334 0.6      ]
 [1.        0.5      ]], shape=(2, 2), dtype=float32)
A + 1 =  tf.Tensor(
[[5. 4.]
 [2. 2.]], shape=(2, 2), dtype=float32)


### Tensor shpaes 

Tensors have shapes. Some vocabulary:

- **Shape**: The length (number of elements) of each of the axes of a tensor.
- **Rank**: Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
- **Axis** or **Dimension**: A particular dimension of a tensor.
- **Size**: The total number of items in the tensor, the product shape vector.


In [8]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])

In [9]:
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


(참고) While axes are often referred to by their indices, you should always keep track of the meaning of each. Often axes are ordered from global to local: The batch axis first, followed by spatial dimensions, and features for each location last. This way feature vectors are contiguous regions of memory.

<img src="https://www.tensorflow.org/guide/images/tensor/shape2.png" align="center" width="400"/>

### Indexing

#### Single-axis indexing
TensorFlow follows standard Python indexing rules, similar to indexing a list or a string in Python, and the basic rules for NumPy indexing.

- indexes start at `0`
- negative indices count backwards from the end
- colons, `:`, are used for slices: `start:stop:step`

In [10]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


Indexing with a scalar removes the axis:

In [11]:
print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())

First: 0
Second: 1
Last: 34


Indexing with a `:` slice keeps the axis:

In [13]:
print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())

Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4: [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


##### Multi-axis indexing

Higher rank tensors are indexed by passing multiple indices.

The exact same rules as in the single-axis case apply to each axis independently.




In [14]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)

print(rank_2_tensor.numpy())

[[1. 2.]
 [3. 4.]
 [5. 6.]]


Passing an integer for each index, the result is a scalar.

In [15]:
# Pull out a single value from a 2-rank tensor
print(rank_2_tensor[1, 1].numpy())

4.0


In [16]:
# Get row and column tensors
print("Second row:", rank_2_tensor[1, :].numpy())
print("Second column:", rank_2_tensor[:, 1].numpy())
print("Last row:", rank_2_tensor[-1, :].numpy())
print("First item in last column:", rank_2_tensor[0, -1].numpy())
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")

Second row: [3. 4.]
Second column: [2. 4. 6.]
Last row: [5. 6.]
First item in last column: 2.0
Skip the first row:
[[3. 4.]
 [5. 6.]] 



In [17]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [18]:
print(rank_3_tensor[:, :, 4])

tf.Tensor(
[[ 4  9]
 [14 19]
 [24 29]], shape=(3, 2), dtype=int32)


<img src="https://www.tensorflow.org/guide/images/tensor/index1.png" align="center" width="400"/>

### Manipulating Shapes

Reshaping a tensor is of great utility.

In [19]:
# Shape returns a `TensorShape` object that shows the size along each axis
x = tf.constant([[1], [2], [3]])
print(x.shape)

(3, 1)


In [20]:
# Convert this object into a Python list
print(x.shape.as_list())

[3, 1]


We can reshape a tensor into a new shape. The `tf.reshape` operation is fast and cheap as the underlying data does not need to be duplicated.

In [21]:
# Reshape a tensor to a new shape.
reshaped = tf.reshape(x, [1, 3])

print(x.shape)
print(reshaped.shape)

(3, 1)
(1, 3)


The data maintains its layout in memory and a new tensor is created, with the requested shape, pointing to the same data. TensorFlow uses C-style "row-major" memory ordering, where incrementing the rightmost index corresponds to a single step in memory.

In [23]:
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


If we flatten a tensor we can see what order it is laid out in memory.

In [24]:
# A `-1` passed in the `shape` argument says "Whatever fits".
print(tf.reshape(rank_3_tensor, [-1]))

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32)


ypically the only reasonable use of `tf.reshape` is to combine or split adjacent axes (or add/remove 1s).

For this 3x2x5 tensor, reshaping to (3x2)x5 or 3x(2x5) are both reasonable things to do, as the slices do not mix:

In [26]:
print(tf.reshape(rank_3_tensor, [3*2, 5]))
print(tf.reshape(rank_3_tensor, [3, -1]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32)
tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


<img src="https://www.tensorflow.org/guide/images/tensor/reshape-before.png" align="center" /> <img src="https://www.tensorflow.org/guide/images/tensor/reshape-good1.png" align="center" /> <img src="https://www.tensorflow.org/guide/images/tensor/reshape-good2.png" align="center" />

### String tesnors 

`tf.string` is a dtype, which is to say you can represent data as strings (variable-length byte arrays) in tensors.

The strings are atomic and cannot be indexed the way Python strings are. The length of the string is not one of the axes of the tensor. See `tf.strings` for functions to manipulate them.

Here is a scalar string tensor:

In [28]:
# Tensors can be strings, too here is a scalar string.
scalar_string_tensor = tf.constant("Gray wolf")
print(scalar_string_tensor)

tf.Tensor(b'Gray wolf', shape=(), dtype=string)


In the above printout the `b` prefix indicates that `tf.string` dtype is not a unicode string, but a byte-string.

In [29]:
# If we have three string tensors of different lengths, this is OK.
tensor_of_strings = tf.constant(["Gray wolf",
                                 "Quick brown fox",
                                 "Lazy dog"])

# Note that the shape is (3,). The string length is not included.
print(tensor_of_strings)

tf.Tensor([b'Gray wolf' b'Quick brown fox' b'Lazy dog'], shape=(3,), dtype=string)


<img src="https://www.tensorflow.org/guide/images/tensor/strings.png" align="center" />

We can also obtain the numbers in the string by utilizing `tf.string.to_number`.

In [30]:
text = tf.constant("1 10 100")
print(tf.strings.to_number(tf.strings.split(text, " ")))

tf.Tensor([  1.  10. 100.], shape=(3,), dtype=float32)


### Tensor slicing 
 
#### Extract tensor slices
Perform NumPy-like tensor slicing using `tf.slice`.

In [31]:
t1 = tf.constant([0, 1, 2, 3, 4, 5, 6, 7])
print(t1)

print(tf.slice(t1,
               begin=[1],
               size=[3]))

tf.Tensor([0 1 2 3 4 5 6 7], shape=(8,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


Alternatively, you can use a more Pythonic syntax. Note that tensor slices are evenly spaced over a start-stop range.


In [ ]:
print(t1[1:4], '\n')
print(t1[-3:])

We can use `tf.slice` on higher dimensional tensors as well.

In [ ]:
t2 = tf.constant([[[1, 3, 5, 7],
                   [9, 11, 13, 15]],
                  [[17, 19, 21, 23],
                   [25, 27, 29, 31]]
                  ])
print(t2)
print(tf.slice(t2,
               begin=[1, 1, 0],
               size=[1, 1, 2]))

We can also use `tf.strided_slice` to extract slices of tensors by 'striding' over the tensor dimensions.

Use `tf.gather` to extract specific indices from a single axis of a tensor.

In [32]:
print(tf.gather(t1,
                indices=[0, 3, 6]))

tf.Tensor([0 3 6], shape=(3,), dtype=int32)


<img src="https://www.tensorflow.org/guide/images/tf_slicing/slice_1d_3.png" align="center" />

In [ ]:
alphabet = tf.constant(list('abcdefghijklmnopqrstuvwxyz'))

print(tf.gather(alphabet,
                indices=[2, 0, 19, 18]))

<img src="https://www.tensorflow.org/guide/images/tf_slicing/gather_1.png" align="center" />

To extract slices from multiple axes of a tensor, use `tf.gather_nd`. This is useful when you want to gather the elements of a matrix as opposed to just its rows or columns.

In [ ]:
t3 = tf.constant([[0, 5],
                  [1, 6],
                  [2, 7],
                  [3, 8],
                  [4, 9]])
print(t3)
print(tf.gather_nd(t3,
                   indices=[[2], [3], [0]]))

<img src="https://www.tensorflow.org/guide/images/tf_slicing/gather_2.png" align="center" />

In [33]:
t4 = np.reshape(np.arange(18), [2, 3, 3])
print(t4)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [34]:
print(tf.gather_nd(t4,
                   indices=[[0, 0, 0], [1, 2, 1]]))

tf.Tensor([ 0 16], shape=(2,), dtype=int64)


In [35]:
print(tf.gather_nd(t4,
                   indices=[[[0, 0], [0, 2]], [[1, 0], [1, 2]]]))

tf.Tensor(
[[[ 0  1  2]
  [ 6  7  8]]

 [[ 9 10 11]
  [15 16 17]]], shape=(2, 2, 3), dtype=int64)


#### Insert data into tensors

Use `tf.scatter_nd` to insert data at specific slices/indices of a tensor. Note that the tensor into which you insert values is zero-initialized.

In [36]:
t6 = tf.constant([10])
indices = tf.constant([[1], [3], [5], [7], [9]])
data = tf.constant([2, 4, 6, 8, 10])

print(tf.scatter_nd(indices=indices,
                    updates=data,
                    shape=t6))

tf.Tensor([ 0  2  0  4  0  6  0  8  0 10], shape=(10,), dtype=int32)


In [37]:
t2 = tf.constant([[0, 1, 2, 3, 4],
                  [5, 6, 7, 8, 9],
                  [10, 11, 12, 13, 14],
                  [15, 16, 17, 18, 19]])

new_indices = tf.constant([[0, 2], [2, 1], [3, 3]])
t7 = tf.gather_nd(t2, indices=new_indices)
print(t7)

tf.Tensor([ 2 11 18], shape=(3,), dtype=int32)


In [38]:
t8 = tf.scatter_nd(indices=new_indices, updates=t7, shape=tf.constant([4, 5]))
print(t8)

tf.Tensor(
[[ 0  0  2  0  0]
 [ 0  0  0  0  0]
 [ 0 11  0  0  0]
 [ 0  0  0 18  0]], shape=(4, 5), dtype=int32)


To insert data into a tensor with pre-existing values, use `tf.tensor_scatter_nd_add`.

In [39]:
t11 = tf.constant([[2, 7, 0],
                   [9, 0, 1],
                   [0, 3, 8]])

# Convert the tensor into a magic square by inserting numbers at appropriate indices

t12 = tf.tensor_scatter_nd_add(t11,
                               indices=[[0, 2], [1, 1], [2, 0]],
                               updates=[6, 5, 4])

print(t12)

tf.Tensor(
[[2 7 6]
 [9 5 1]
 [4 3 8]], shape=(3, 3), dtype=int32)


Similarly, use `tf.tensor_scatter_nd_sub` to subtract values from a tensor with pre-existing values.

In [40]:
# Convert the tensor into an identity matrix
t13 = tf.tensor_scatter_nd_sub(t11,
                               indices=[[0, 0], [0, 1], [1, 0], [1, 1], [1, 2], [2, 1], [2, 2]],
                               updates=[1, 7, 9, -1, 1, 3, 7])

print(t13)

tf.Tensor(
[[1 0 0]
 [0 1 0]
 [0 0 1]], shape=(3, 3), dtype=int32)


Use `tf.tensor_scatter_nd_min` to copy element-wise minimum values from one tensor to another.

In [41]:
t14 = tf.constant([[-2, -7, 0],
                   [-9, 0, 1],
                   [0, -3, -8]])

t15 = tf.tensor_scatter_nd_min(t14,
                               indices=[[0, 2], [1, 1], [2, 0]],
                               updates=[-6, -5, -4])

print(t15)

tf.Tensor(
[[-2 -7 -6]
 [-9 -5  1]
 [-4 -3 -8]], shape=(3, 3), dtype=int32)


Similarly, use `tf.tensor_scatter_nd_max` to copy element-wise maximum values from one tensor to another.

In [42]:
t16 = tf.tensor_scatter_nd_max(t14,
                               indices=[[0, 2], [1, 1], [2, 0]],
                               updates=[6, 5, 4])

print(t16)

tf.Tensor(
[[-2 -7  6]
 [-9  5  1]
 [ 4 -3 -8]], shape=(3, 3), dtype=int32)


### Dynamic control flow

As you've seen, TensorFlow now supports an imperative programming style, and that's all because of Eager. As another example of the power of Eager, let's take a look at how we can build a dynamic model that uses Python flow control. Here's an example of the [Fizz buzz](https://en.wikipedia.org/wiki/Fizz_buzz) using TensorFlow’s arithmetic operations. Such dynamic behavior is not possible in past versions of TensorFlow (up to v1.4)!

In [43]:
def fizzbuzz(max_num):
    counter = tf.constant(0)
    max_num = tf.convert_to_tensor(max_num)
    
    for num in range(1, max_num.numpy() + 1):
        num = tf.constant(num)
        if int(num % 3) == 0 and int(num % 5) == 0:
            print('FizzBuzz')
        elif int(num % 3) == 0:
            print('Fizz')
        elif int(num % 5) == 0:
            print('Buzz')
        else:
            print(num.numpy())
            
        counter += 1

In [44]:
fizzbuzz(15)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz


## GPU-based Computiation 

On a typical system, there are multiple computing devices. 

In TensorFlow, the supported device types are **CPU** and **GPU**. 

They are represented as strings. For example:

* `'/cpu:0'`: The CPU of your machine.
* `'/gpu:0'`: The GPU of your machine, if you have one.
* `'/gpu:1'`: The second GPU of your machine, etc.
    
If a TensorFlow operation has both **CPU** and **GPU** implementations, the GPU devices will be given priority when the operation is assigned to a device. 

For example, `matmul` has both CPU and GPU kernels. On a system with devices `cpu:0` and `gpu:0`, `gpu:0` will be selected to run `matmul`.    

### Using multiple GPUs

In [45]:
from tensorflow.python.client import device_lib

def get_available_gpus():
    local_device_protos = device_lib.list_local_devices()
    return [x.name for x in local_device_protos if x.device_type == 'GPU']

available_gpus = get_available_gpus()
print(available_gpus)

['/device:GPU:0', '/device:GPU:1']


In [46]:
c = []
if tf.test.is_gpu_available():
    for d in available_gpus:
        with tf.device(d):
            a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3])
            b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2])
            c.append(tf.matmul(a, b))
            
    with tf.device('/cpu:0'):
        result = tf.add_n(c)
        print(result)

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
tf.Tensor(
[[ 44.  56.]
 [ 98. 128.]], shape=(2, 2), dtype=float32)


In [47]:
import time

with tf.device('/cpu:0'):
    a = tf.random.normal((512, 64, 32, 32))
    b = tf.random.normal((512, 64, 32, 32))
    
    start_time = time.time()
    tf.matmul(a, b)
    end_time = time.time()

print('Elapsed time: {:.4f}s'.format(end_time - start_time))

Elapsed time: 0.2850s


In [48]:
with tf.device('/gpu:0'):
    a = tf.random.normal((512, 64, 32, 32))
    b = tf.random.normal((512, 64, 32, 32))
    
    start_time = time.time()
    tf.matmul(a, b)
    end_time = time.time()
    
print('Elapsed time: {:.4f}s'.format(end_time - start_time))

Elapsed time: 0.0002s


---

### More on Tensorflow

[Official API Documentation](https://www.tensorflow.org/tutorials)